[project]
name = "maya_usd_export"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.7"
dependencies = []

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
